# Generated by Django 2.2.6 on 2021-05-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210514_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created', 'id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', '-id']},
        ),
    ]
